name: Go Lint & Build Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Run go fmt
        run: |
          fmt_result=$(gofmt -l .)
          if [ -n "$fmt_result" ]; then
            echo "The following files need formatting:"
            echo "$fmt_result"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Build code
        run: go build ./...
